
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




public class TelaPrincipal extends javax.swing.JFrame {
    private String sobre;
    private String nome;
    private Image i;
    ImageIcon img; 
    /**
     * Creates new form Joao
     */
    public TelaPrincipal() {
        img = new ImageIcon(getClass().getResource("/Images/Caipira.png"));
        URL u = getClass().getResource("/Images/Alonso.png");
        i = Toolkit.getDefaultToolkit().getImage(u);
        this.setIconImage(i);
        setTitle("Sasp - Soletre as Palavras");
        initComponents();
        this.setSize(600,520);
        
        sobre = "--------------REGRAS--------------------\n" 
                +"No jogo você tem 10 vidas \n"
                +"São 3 fases: Fácil, Média e Difícil \n"
                +"Você precisa acertar um total de 30 \n"
                +"palavras para completar o jogo \n"
                +"A cada 5 acertos, ganha uma vida \n"
                +"1 acerto equivale a mais 3 pontos \n"
                +"1 erro equivale a menos 1 ponto \n"
                +"Você pode ver o significado da palavra \n"
                +"uma vez \n"
                +"Criação e produção : \n"
                +"Lucas Almeida e Pedro Guilherme";
        
    }
    
    public static String leitura()
    throws FileNotFoundException, IOException
    
    {
        FileReader in = new FileReader("dados.txt");
        BufferedReader bf = new BufferedReader(in);
        StringBuffer str = new StringBuffer();
        while(bf.ready()){
            str.append(bf.readLine());
            str.append("\n");
        }
        return str.toString();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtNick = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Scores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 160, 40));

        btnIniciar.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 160, 40));

        jButton3.setText("Sobre");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 160, 40));

        txtNick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNickMouseClicked(evt);
            }
        });
        txtNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNickActionPerformed(evt);
            }
        });
        getContentPane().add(txtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 190, -1));

        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setText("Digite seu NickGame abaixo");
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FundoPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if(txtNick.getText().equals("")){
            /*JOptionPane.showMessageDialog(this, "Para iniciar digite seu Nome de Usuário",
                    "Ops", JOptionPane.INFORMATION_MESSAGE);*/
            JOptionPane.showMessageDialog(this, "Para iniciar, digite seu Nome de Usuário", "Ops", WIDTH, img);
            
        }else{
                                                   
        nome = txtNick.getText();
        TelaAvatar telaa = new TelaAvatar(nome);
        telaa.setVisible(true);
        dispose();      
    
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNickActionPerformed
        
    }//GEN-LAST:event_txtNickActionPerformed

    private void txtNickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNickMouseClicked
        lblMensagem.setVisible(false);
    }//GEN-LAST:event_txtNickMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JOptionPane.showMessageDialog(this, leitura(), "Scores", WIDTH,img);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível fazer a leitura dos arquivos", "Erro", WIDTH, img);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(this, sobre,
                    "Parabéns, você ganhou!! ", JOptionPane.INFORMATION_MESSAGE,img);
    }//GEN-LAST:event_jButton3ActionPerformed

    
        
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtNick;
    // End of variables declaration//GEN-END:variables
}
