/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import Main.Principal;


import javax.swing.JLabel;
import Entidade.Jogador;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Grafith 2001
 */
public class TelaAvatar extends javax.swing.JFrame {
    
    private int avatar;
    private String nome;
    public TelaAvatar(String nome) {
        URL u = getClass().getResource("/Images/IconJanela.png");
        Image i = Toolkit.getDefaultToolkit().getImage(u);
        this.setIconImage(i);
        setTitle("Sasp - Soletre as Palavras");
        initComponents();
        this.setSize(600,520);
        this.nome = nome;
    }
    
    public int getAvatar() {
        return avatar;
    }
    
    
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnM1 = new javax.swing.JButton();
        btnM2 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Humblle Rought All Caps", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escolha seu avatar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 400, 80));

        btnM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Moça1.png"))); // NOI18N
        btnM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 160, 177));

        btnM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Moça2.png"))); // NOI18N
        btnM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 160, 177));

        btnH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nerd_1.png"))); // NOI18N
        btnH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 160, 177));

        btnH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rapaz.png"))); // NOI18N
        btnH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 160, 177));

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fundo.jpg"))); // NOI18N
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 604, 497));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
   
    
    
    private void btnH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH1ActionPerformed
        avatar = 1;
        TelaGameplay tela = new TelaGameplay(1,nome);
        
        tela.setVisible(true);
        dispose();       
    
        
    }//GEN-LAST:event_btnH1ActionPerformed

    private void btnH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH2ActionPerformed
        avatar = 3;
        TelaGameplay tela = new TelaGameplay(3,nome);
        
        tela.setVisible(true);
        
        dispose();       
    
    }//GEN-LAST:event_btnH2ActionPerformed

    private void btnM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM1ActionPerformed
        avatar = 2;
        TelaGameplay tela = new TelaGameplay(2,nome);
        
        tela.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btnM1ActionPerformed

    private void btnM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM2ActionPerformed
        avatar = 4;
        TelaGameplay tela = new TelaGameplay(4,nome);
        
        tela.setVisible(true);
        
        dispose(); 
    }//GEN-LAST:event_btnM2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnH2;
    private javax.swing.JButton btnM1;
    private javax.swing.JButton btnM2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelFundo;
    // End of variables declaration//GEN-END:variables
}
